apiVersion: v1
kind: Service
metadata:
  name: bi-api-service
  labels:
    app.kubernetes.io/name: business-intelligence-api
    app.kubernetes.io/part-of: business-opportunity-platform
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: business-intelligence-api
